# version: '3.8'

# services:
#   postgres:
#     image: postgres:latest
#     container_name: postgres_db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: chat_app
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - chat_network

# volumes:
#   postgres_data:

# networks:
#   chat_network:
#     driver: bridge


version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: chat_client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - chat_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat_backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=chat_app
      - DB_PASSWORD=password
      - DB_PORT=5432
      - JWT_SECRET=myverysecuresecret
      - PORT=5000
    depends_on:
      - postgres
    networks:
      - chat_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat_network

volumes:
  postgres_data:

networks:
  chat_network:
    driver: bridge